services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - ./backend/.env
        ports:
            - '5050:5050'
            - '3030:3030'

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - '4040:4040'
